### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by mikeynap** [urzds/ipmitool-docker#1]
Is this something I could push to dockerhub for use in a project? I would link back to this repo.
 Does that violate any license or anything?

**Comment by ghost** [comment]
It should not violate any license, but I am already building ipmitool and upload it to Docker Hub:
1. https://travis-ci.org/urzds/ipmitool-docker
2. https://hub.docker.com/r/urzds/ipmitool

Please close this issue, if that repository suits your needs or you are satisfied with this answer.

**Comment by sujithemmanuel** [comment]
> It should not violate any license, but I am already building ipmitool and upload it to Docker Hub:
> 
> 1. https://travis-ci.org/urzds/ipmitool-docker
> 2. https://hub.docker.com/r/urzds/ipmitool
> 
> Please close this issue, if that repository suits your needs or you are satisfied with this answer.

The build has been failing for quite a while now. https://hub.docker.com/r/urzds/ipmitool is giving 404. Could you please take a look?

**Comment by ghost** [comment]
I've moved it to Quay: https://quay.io/repository/urzds/ipmitool
